"""Add game_user Association Table

Revision ID: a77b3afb4c36
Revises: c60ac647b312
Create Date: 2023-09-02 22:06:55.829721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77b3afb4c36'
down_revision = 'c60ac647b312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
